### ISSUE TITLE
width 930px height 388px의 영역에 6 * 4 테이블로 구성된다.

### ISSUE THREAD

**Issue by youzysu** [youzysu/fe-max--newsstand#5]
## SubTasks
- [x] allpressList 전체 96개의 press data를 fetch 받는다.
- [x] allpressList와 현재 페이지의 gridPressStartIndex를 인자로 받아 테이블을 구성한다.
- [x] GridViewer 컴포넌트는 table 태그, 각 Grid는 td 태그, 4개의 row로 이루어진다.
- [x] 각 테이블의 셀에는 언론사 브랜드 마크가 중앙에 배치된다. 

![image](https://github.com/youzysu/fe-max--newsstand/assets/111998760/0ce56d15-9d99-46d6-8d2e-f42d3d456a92)

**Comment by youzysu** [comment]
GridViewer 컴포넌트에는 24개 Press data를 담은 PressProps를 전달한다. (Rendering에 필요한 정보만 전달)

**Comment by youzysu** [comment]
## TroubleShooting

- grid layout 시에는 table 태그라고 해도 border-collapse 속성이 적용되지 않음
- 고민한 방법: table 태그 대신 div 태그로 grid layout 적용하고 border 겹치는 문제 해결하기 (outline, border-bottom 등 겹치지 않게 직접 border 적용)
- 적용한 방법: 기존 계획대로 table 태그로 `border-collapse: collapse;` 적용

```css
.gridViewer {
  width: 930px;
  height: 388px;
  display: grid;
  grid-template-rows: repeat(4, 1fr);
  align-items: center;
  justify-items: center;
}

.gridRow {
  width: 100%;
  height: 100%;
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  align-items: center;
  justify-items: center;
}

.grid {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid var(--color-gray-100);
}

.pressIcon {
  height: 20px;
}

```
